---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lunar.arpan.io
  resources:
  - moons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lunar.arpan.io
  resources:
  - moons/finalizers
  verbs:
  - update
- apiGroups:
  - lunar.arpan.io
  resources:
  - moons/status
  verbs:
  - get
  - patch
  - update
