# permissions for end users to edit solars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: solar-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: chasing-sun
    app.kubernetes.io/part-of: chasing-sun
    app.kubernetes.io/managed-by: kustomize
  name: solar-editor-role
rules:
- apiGroups:
  - lunar.arpan.io
  resources:
  - solars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lunar.arpan.io
  resources:
  - solars/status
  verbs:
  - get
